export const baseStations = [
  {
    id: 1,
    name: "Trạm BTS Quận 1 - A",
    technician: "Nguyễn Văn A",
    status: "ONLINE",
    location: "Quận 1, TP.HCM",
    signal: 95,
    type: "BTS",
    phone: "0901000001",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7769, 106.7009],
    range: 400,
  },
  {
    id: 2,
    name: "Trạm 5G Quận 1 - B",
    technician: "Lê Thị B",
    status: "ONLINE",
    location: "Quận 1, TP.HCM",
    signal: 92,
    type: "5G",
    phone: "0901000002",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7775, 106.6988],
    range: 350,
  },
  {
    id: 3,
    name: "Trạm NodeB Quận 3 - A",
    technician: "Phạm Văn C",
    status: "ONLINE",
    location: "Quận 3, TP.HCM",
    signal: 90,
    type: "NodeB",
    phone: "0901000003",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7828, 106.6955],
    range: 480,
  },
  {
    id: 4,
    name: "Trạm BTS Quận 3 - B",
    technician: "Trần Thị D",
    status: "ONLINE",
    location: "Quận 3, TP.HCM",
    signal: 88,
    type: "BTS",
    phone: "0901000004",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.785, 106.6932],
    range: 320,
  },
  {
    id: 5,
    name: "Trạm Repeater Quận 5 - A",
    technician: "Võ Văn E",
    status: "MAINTENANCE",
    location: "Quận 5, TP.HCM",
    signal: 60,
    type: "Repeater",
    phone: "0901000005",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7562, 106.6645],
    range: 400,
  },
  {
    id: 6,
    name: "Trạm 5G Quận 5 - B",
    technician: "Ngô Thị F",
    status: "ONLINE",
    location: "Quận 5, TP.HCM",
    signal: 85,
    type: "5G",
    phone: "0901000006",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7584, 106.6671],
    range: 300,
  },
  {
    id: 7,
    name: "Trạm BTS Quận 4 - A",
    technician: "Đặng Văn G",
    status: "ONLINE",
    location: "Quận 4, TP.HCM",
    signal: 87,
    type: "BTS",
    phone: "0901000007",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7633, 106.7044],
    range: 450,
  },
  {
    id: 8,
    name: "Trạm NodeB Quận 4 - B",
    technician: "Hồ Thị H",
    status: "OFFLINE",
    location: "Quận 4, TP.HCM",
    signal: 0,
    type: "NodeB",
    phone: "0901000008",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.762, 106.7092],
    range: 310,
  },
  {
    id: 9,
    name: "Trạm BTS Bình Thạnh - A",
    technician: "Lưu Văn I",
    status: "ONLINE",
    location: "Quận Bình Thạnh, TP.HCM",
    signal: 89,
    type: "BTS",
    phone: "0901000009",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8057, 106.7136],
    range: 420,
  },
  {
    id: 10,
    name: "Trạm Repeater Bình Thạnh - B",
    technician: "Mai Thị J",
    status: "MAINTENANCE",
    location: "Quận Bình Thạnh, TP.HCM",
    signal: 50,
    type: "Repeater",
    phone: "0901000010",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8065, 106.7105],
    range: 370,
  },
  {
    id: 11,
    name: "Trạm NodeB Phú Nhuận - A",
    technician: "Trương Văn K",
    status: "ONLINE",
    location: "Quận Phú Nhuận, TP.HCM",
    signal: 93,
    type: "NodeB",
    phone: "0901000011",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7992, 106.6806],
    range: 480,
  },
  {
    id: 12,
    name: "Trạm BTS Phú Nhuận - B",
    technician: "Đỗ Thị L",
    status: "ONLINE",
    location: "Quận Phú Nhuận, TP.HCM",
    signal: 91,
    type: "BTS",
    phone: "0901000012",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8015, 106.6829],
    range: 340,
  },
  {
    id: 13,
    name: "Trạm 5G Tân Bình - A",
    technician: "Nguyễn Văn M",
    status: "ONLINE",
    location: "Quận Tân Bình, TP.HCM",
    signal: 90,
    type: "5G",
    phone: "0901000013",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8011, 106.6526],
    range: 430,
  },
  {
    id: 14,
    name: "Trạm NodeB Tân Bình - B",
    technician: "Lê Thị N",
    status: "ONLINE",
    location: "Quận Tân Bình, TP.HCM",
    signal: 88,
    type: "NodeB",
    phone: "0901000014",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8033, 106.6581],
    range: 350,
  },
  {
    id: 15,
    name: "Trạm BTS Quận 10 - A",
    technician: "Phan Văn O",
    status: "ONLINE",
    location: "Quận 10, TP.HCM",
    signal: 90,
    type: "BTS",
    phone: "0901000015",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7746, 106.6674],
    range: 390,
  },
  {
    id: 16,
    name: "Trạm Repeater Quận 10 - B",
    technician: "Cao Thị P",
    status: "OFFLINE",
    location: "Quận 10, TP.HCM",
    signal: 0,
    type: "Repeater",
    phone: "0901000016",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.776, 106.665],
    range: 310,
  },
  {
    id: 17,
    name: "Trạm 5G Quận 11 - A",
    technician: "Trịnh Văn Q",
    status: "ONLINE",
    location: "Quận 11, TP.HCM",
    signal: 85,
    type: "5G",
    phone: "0901000017",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7629, 106.6458],
    range: 480,
  },
  {
    id: 18,
    name: "Trạm NodeB Quận 11 - B",
    technician: "Vũ Thị R",
    status: "ONLINE",
    location: "Quận 11, TP.HCM",
    signal: 87,
    type: "NodeB",
    phone: "0901000018",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.765, 106.6485],
    range: 360,
  },
  {
    id: 19,
    name: "Trạm BTS Quận Tân Phú - A",
    technician: "Nguyễn Văn S",
    status: "ONLINE",
    location: "Quận Tân Phú, TP.HCM",
    signal: 82,
    type: "BTS",
    phone: "0901000019",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7911, 106.6237],
    range: 490,
  },
  {
    id: 20,
    name: "Trạm 5G Quận Tân Phú - B",
    technician: "Trần Thị T",
    status: "ONLINE",
    location: "Quận Tân Phú, TP.HCM",
    signal: 86,
    type: "5G",
    phone: "0901000020",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7933, 106.6205],
    range: 350,
  },
  {
    id: 101,
    name: "Trạm BTS Q1 - Nguyễn Huệ",
    technician: "Nguyễn Văn Khoa",
    status: "ONLINE",
    location: "Quận 1, TP.HCM",
    signal: 95,
    type: "BTS",
    phone: "0901000001",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7738, 106.7044],
    range: 450,
  },
  {
    id: 102,
    name: "Trạm 5G Q1 - Tôn Đức Thắng",
    technician: "Trần Thị Loan",
    status: "OFFLINE",
    location: "Quận 1, TP.HCM",
    signal: 0,
    type: "5G",
    phone: "0901000002",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7806, 106.7096],
    range: 400,
  },
  {
    id: 103,
    name: "Trạm NodeB Q1 - Đồng Khởi",
    technician: "Lê Quang Huy",
    status: "ONLINE",
    location: "Quận 1, TP.HCM",
    signal: 88,
    type: "NodeB",
    phone: "0901000003",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7761, 106.7032],
    range: 350,
  },
  {
    id: 104,
    name: "Trạm Repeater Q1 - Bùi Viện",
    technician: "Võ Thị Mai",
    status: "MAINTENANCE",
    location: "Quận 1, TP.HCM",
    signal: 45,
    type: "Repeater",
    phone: "0901000004",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7683, 106.6934],
    range: 300,
  },
  {
    id: 105,
    name: "Trạm BTS Q2 - Thảo Điền",
    technician: "Phan Văn Dũng",
    status: "ONLINE",
    location: "Quận 2, TP.HCM",
    signal: 90,
    type: "BTS",
    phone: "0901000005",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8036, 106.7379],
    range: 470,
  },
  {
    id: 106,
    name: "Trạm NodeB Q2 - Xa Lộ Hà Nội",
    technician: "Nguyễn Thị Hạnh",
    status: "ONLINE",
    location: "Quận 2, TP.HCM",
    signal: 82,
    type: "NodeB",
    phone: "0901000006",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7961, 106.7401],
    range: 490,
  },
  {
    id: 107,
    name: "Trạm 5G Q2 - An Phú",
    technician: "Lê Minh Tâm",
    status: "MAINTENANCE",
    location: "Quận 2, TP.HCM",
    signal: 33,
    type: "5G",
    phone: "0901000007",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.8003, 106.7455],
    range: 310,
  },
  {
    id: 108,
    name: "Trạm Repeater Q2 - Thủ Thiêm",
    technician: "Trịnh Hoài Nam",
    status: "ONLINE",
    location: "Quận 2, TP.HCM",
    signal: 77,
    type: "Repeater",
    phone: "0901000008",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7832, 106.7247],
    range: 330,
  },
  {
    id: 109,
    name: "Trạm BTS Q3 - CMT8",
    technician: "Đặng Quốc Việt",
    status: "ONLINE",
    location: "Quận 3, TP.HCM",
    signal: 91,
    type: "BTS",
    phone: "0901000009",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7801, 106.6782],
    range: 495,
  },
  {
    id: 110,
    name: "Trạm NodeB Q3 - Võ Văn Tần",
    technician: "Phạm Thị Hòa",
    status: "OFFLINE",
    location: "Quận 3, TP.HCM",
    signal: 0,
    type: "NodeB",
    phone: "0901000010",
    avatar: "/api/placeholder/40/40",
    coordinates: [10.7765, 106.6862],
    range: 460,
  },
];

export const mockBaseStations = [
  {
    name: "Trạm 1",
    ward: "Phường Tân Định",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 2",
    ward: "Phường Tân Định",
    status: "ONLINE",
  },
  {
    name: "Trạm 3",
    ward: "Phường Bến Thành",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 4",
    ward: "Phường Bến Thành",
    status: "OFFLINE",
  },
  {
    name: "Trạm 5",
    ward: "Phường Bến Thành",
    status: "ONLINE",
  },
  {
    name: "Trạm 6",
    ward: "Phường Bến Thành",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 7",
    ward: "Phường Chợ Quán",
    status: "ONLINE",
  },
  {
    name: "Trạm 8",
    ward: "Phường Chợ Quán",
    status: "OFFLINE",
  },
  {
    name: "Trạm 9",
    ward: "Phường Chợ Quán",
    status: "ONLINE",
  },
  {
    name: "Trạm 10",
    ward: "Phường Chợ Quán",
    status: "ONLINE",
  },
  {
    name: "Trạm 11",
    ward: "Phường Chợ Quán",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 12",
    ward: "Phường Chợ Lớn",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 13",
    ward: "Phường Chợ Lớn",
    status: "ONLINE",
  },
  {
    name: "Trạm 14",
    ward: "Phường Chợ Lớn",
    status: "OFFLINE",
  },
  {
    name: "Trạm 15",
    ward: "Phường Chợ Lớn",
    status: "OFFLINE",
  },
  {
    name: "Trạm 16",
    ward: "Phường Bình Tây",
    status: "ONLINE",
  },
  {
    name: "Trạm 17",
    ward: "Phường Bình Tây",
    status: "OFFLINE",
  },
  {
    name: "Trạm 18",
    ward: "Phường Bình Tây",
    status: "OFFLINE",
  },
  {
    name: "Trạm 19",
    ward: "Phường Bình Tây",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 20",
    ward: "Phường Bình Tây",
    status: "ONLINE",
  },
  {
    name: "Trạm 21",
    ward: "Phường Phú Lâm",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 22",
    ward: "Phường Phú Lâm",
    status: "OFFLINE",
  },
  {
    name: "Trạm 23",
    ward: "Phường Phú Lâm",
    status: "OFFLINE",
  },
  {
    name: "Trạm 24",
    ward: "Phường Phú Lâm",
    status: "ONLINE",
  },
  {
    name: "Trạm 25",
    ward: "Phường Phú Lâm",
    status: "ONLINE",
  },
  {
    name: "Trạm 26",
    ward: "Phường Tân Thuận",
    status: "ONLINE",
  },
  {
    name: "Trạm 27",
    ward: "Phường Tân Thuận",
    status: "ONLINE",
  },
  {
    name: "Trạm 28",
    ward: "Phường Tân Mỹ",
    status: "ONLINE",
  },
  {
    name: "Trạm 29",
    ward: "Phường Tân Mỹ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 30",
    ward: "Phường Tân Mỹ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 31",
    ward: "Phường Tân Mỹ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 32",
    ward: "Phường Tân Mỹ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 33",
    ward: "Phường Tân Hưng",
    status: "ONLINE",
  },
  {
    name: "Trạm 34",
    ward: "Phường Tân Hưng",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 35",
    ward: "Phường Tân Hưng",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 36",
    ward: "Phường Tân Hưng",
    status: "ONLINE",
  },
  {
    name: "Trạm 37",
    ward: "Phường Tân Hưng",
    status: "ONLINE",
  },
  {
    name: "Trạm 38",
    ward: "Phường Chánh Hưng",
    status: "OFFLINE",
  },
  {
    name: "Trạm 39",
    ward: "Phường Chánh Hưng",
    status: "OFFLINE",
  },
  {
    name: "Trạm 40",
    ward: "Phường Hiệp Bình Chánh",
    status: "OFFLINE",
  },
  {
    name: "Trạm 41",
    ward: "Phường Hiệp Bình Chánh",
    status: "OFFLINE",
  },
  {
    name: "Trạm 42",
    ward: "Phường Hiệp Bình Chánh",
    status: "ONLINE",
  },
  {
    name: "Trạm 43",
    ward: "Phường Hiệp Bình Chánh",
    status: "OFFLINE",
  },
  {
    name: "Trạm 44",
    ward: "Phường Hiệp Bình Chánh",
    status: "ONLINE",
  },
  {
    name: "Trạm 45",
    ward: "Phường Linh Đông",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 46",
    ward: "Phường Linh Đông",
    status: "ONLINE",
  },
  {
    name: "Trạm 47",
    ward: "Phường Linh Tây",
    status: "OFFLINE",
  },
  {
    name: "Trạm 48",
    ward: "Phường Linh Tây",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 49",
    ward: "Phường Linh Tây",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 50",
    ward: "Phường Linh Xuân",
    status: "OFFLINE",
  },
  {
    name: "Trạm 51",
    ward: "Phường Linh Xuân",
    status: "ONLINE",
  },
  {
    name: "Trạm 52",
    ward: "Phường Linh Xuân",
    status: "ONLINE",
  },
  {
    name: "Trạm 53",
    ward: "Phường Linh Xuân",
    status: "OFFLINE",
  },
  {
    name: "Trạm 54",
    ward: "Phường Linh Xuân",
    status: "OFFLINE",
  },
  {
    name: "Trạm 55",
    ward: "Phường Trường Thọ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 56",
    ward: "Phường Trường Thọ",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 57",
    ward: "Phường Trường Thọ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 58",
    ward: "Phường Hiệp Phú",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 59",
    ward: "Phường Hiệp Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 60",
    ward: "Phường Hiệp Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 61",
    ward: "Phường Hiệp Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 62",
    ward: "Phường Hiệp Phú",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 63",
    ward: "Phường Tăng Nhơn Phú A",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 64",
    ward: "Phường Tăng Nhơn Phú A",
    status: "OFFLINE",
  },
  {
    name: "Trạm 65",
    ward: "Phường Tăng Nhơn Phú A",
    status: "ONLINE",
  },
  {
    name: "Trạm 66",
    ward: "Phường Tăng Nhơn Phú A",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 67",
    ward: "Phường Tăng Nhơn Phú B",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 68",
    ward: "Phường Tăng Nhơn Phú B",
    status: "OFFLINE",
  },
  {
    name: "Trạm 69",
    ward: "Phường Tăng Nhơn Phú B",
    status: "OFFLINE",
  },
  {
    name: "Trạm 70",
    ward: "Phường Tăng Nhơn Phú B",
    status: "ONLINE",
  },
  {
    name: "Trạm 71",
    ward: "Phường Long Thạnh Mỹ",
    status: "OFFLINE",
  },
  {
    name: "Trạm 72",
    ward: "Phường Long Thạnh Mỹ",
    status: "ONLINE",
  },
  {
    name: "Trạm 73",
    ward: "Phường Long Thạnh Mỹ",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 74",
    ward: "Phường Long Thạnh Mỹ",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 75",
    ward: "Phường Long Thạnh Mỹ",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 76",
    ward: "Phường Tân Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 77",
    ward: "Phường Tân Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 78",
    ward: "Phường Tân Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 79",
    ward: "Phường Thảo Điền",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 80",
    ward: "Phường Thảo Điền",
    status: "ONLINE",
  },
  {
    name: "Trạm 81",
    ward: "Phường Thảo Điền",
    status: "OFFLINE",
  },
  {
    name: "Trạm 82",
    ward: "Phường Thảo Điền",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 83",
    ward: "Phường Thảo Điền",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 84",
    ward: "Phường An Phú",
    status: "ONLINE",
  },
  {
    name: "Trạm 85",
    ward: "Phường An Phú",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 86",
    ward: "Phường An Phú",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 87",
    ward: "Phường Bình An",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 88",
    ward: "Phường Bình An",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 89",
    ward: "Phường Bình An",
    status: "ONLINE",
  },
  {
    name: "Trạm 90",
    ward: "Phường Bình An",
    status: "ONLINE",
  },
  {
    name: "Trạm 91",
    ward: "Phường Bình Trưng Đông",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 92",
    ward: "Phường Bình Trưng Đông",
    status: "ONLINE",
  },
  {
    name: "Trạm 93",
    ward: "Phường Bình Trưng Đông",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 94",
    ward: "Phường Bình Trưng Đông",
    status: "ONLINE",
  },
  {
    name: "Trạm 95",
    ward: "Phường Bình Trưng Tây",
    status: "ONLINE",
  },
  {
    name: "Trạm 96",
    ward: "Phường Bình Trưng Tây",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 97",
    ward: "Phường Bình Trưng Tây",
    status: "OFFLINE",
  },
  {
    name: "Trạm 98",
    ward: "Phường Bình Trưng Tây",
    status: "OFFLINE",
  },
  {
    name: "Trạm 99",
    ward: "Phường Cát Lái",
    status: "ONLINE",
  },
  {
    name: "Trạm 100",
    ward: "Phường Cát Lái",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 101",
    ward: "Phường Thạnh Mỹ Lợi",
    status: "OFFLINE",
  },
  {
    name: "Trạm 102",
    ward: "Phường Thạnh Mỹ Lợi",
    status: "OFFLINE",
  },
  {
    name: "Trạm 103",
    ward: "Phường Thạnh Mỹ Lợi",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 104",
    ward: "Phường An Khánh",
    status: "ONLINE",
  },
  {
    name: "Trạm 105",
    ward: "Phường An Khánh",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 106",
    ward: "Phường An Khánh",
    status: "OFFLINE",
  },
  {
    name: "Trạm 107",
    ward: "Phường An Lợi Đông",
    status: "ONLINE",
  },
  {
    name: "Trạm 108",
    ward: "Phường An Lợi Đông",
    status: "ONLINE",
  },
  {
    name: "Trạm 109",
    ward: "Phường An Lợi Đông",
    status: "ONLINE",
  },
  {
    name: "Trạm 110",
    ward: "Phường Thủ Thiêm",
    status: "MAINTENANCE",
  },
  {
    name: "Trạm 111",
    ward: "Phường Thủ Thiêm",
    status: "OFFLINE",
  },
  {
    name: "Trạm 112",
    ward: "Phường Thủ Thiêm",
    status: "ONLINE",
  },
  {
    name: "Trạm 113",
    ward: "Phường Thủ Thiêm",
    status: "ONLINE",
  },
];
